spring:
  application:
    name: poss
  datasource:
    url: jdbc:postgresql://localhost:5432/pos-api
    username: admin-poss
    password: poss
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true


